//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alm_Articulo
    {
        public string Pub_Empr_Codigo { get; set; }
        public string Alm_Arti_Codigo { get; set; }
        public string Alm_Arti_Descripcion { get; set; }
        public string Alm_Arti_Abreviatura { get; set; }
        public string Alm_ARub_Codigo { get; set; }
        public string Alm_UMed_Codigo { get; set; }
        public Nullable<decimal> Alm_Arti_TiempoVida { get; set; }
        public string Alm_Arti_ExigeSerie { get; set; }
        public Nullable<decimal> Alm_Arti_PrecioUnitario { get; set; }
        public string Alm_Arti_Factor_UMed_Codigo { get; set; }
        public Nullable<decimal> Alm_Arti_Factor_Multi { get; set; }
        public Nullable<decimal> Alm_Arti_Factor_Divi { get; set; }
        public string Pub_Esta_Codigo { get; set; }
        public string Alm_Arti_UsuCrea { get; set; }
        public Nullable<System.DateTime> Alm_Arti_FecCrea { get; set; }
        public string Alm_Arti_UsuModi { get; set; }
        public Nullable<System.DateTime> Alm_Arti_FecModi { get; set; }
        public int Alm_Arti_Identidad { get; set; }
        public string Alm_Arti_ExigeMedidor { get; set; }
        public string Alm_Arti_ExigeVencimiento { get; set; }
        public string Alm_Arti_ExigeKardex { get; set; }
        public string Alm_Arti_HojaRecorrido { get; set; }
        public string Alm_Arti_Facturable { get; set; }
        public Nullable<decimal> Alm_Arti_StockMinimo { get; set; }
        public string Alm_Arti_CodigoFabricacion { get; set; }
        public string Alm_Arti_CodigoBarra { get; set; }
        public string Alm_Arti_Menudo { get; set; }
        public string Alm_Arti_Particionado { get; set; }
        public string Alm_Arti_Servicio { get; set; }
        public Nullable<decimal> Alm_Arti_PrecioPromedio { get; set; }
        public Nullable<decimal> Alm_Arti_PrecioPromAnterior { get; set; }
        public Nullable<decimal> Alm_Arti_PrecioUnitario_Soles { get; set; }
        public Nullable<decimal> alm_arti_Proveedor_1_Precio { get; set; }
        public string alm_arti_Proveedor_1 { get; set; }
        public Nullable<decimal> alm_arti_Proveedor_2_Precio { get; set; }
        public string alm_arti_Proveedor_2 { get; set; }
        public Nullable<decimal> alm_arti_Proveedor_3_Precio { get; set; }
        public string alm_arti_Proveedor_3 { get; set; }
        public Nullable<decimal> alm_arti_Proveedor_Precio_PPP { get; set; }
        public Nullable<decimal> alm_arti_Proveedor_Precio_PPM { get; set; }
    }
}
