//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pub_Usuarios
    {
        public string Pub_Usua_Nombre { get; set; }
        public string Pub_Usua_Codigo { get; set; }
        public string Pub_Usua_Login { get; set; }
        public string Pub_Usua_Clave { get; set; }
        public string Pub_Usua_Cargo { get; set; }
        public string Pub_Usua_Email { get; set; }
        public string Pub_Usua_Adm { get; set; }
        public string Pub_Usua_Sis { get; set; }
        public string Pub_Esta_Codigo { get; set; }
        public string Pub_Usua_UsuCrea { get; set; }
        public Nullable<System.DateTime> Pub_Usua_FecCrea { get; set; }
        public string Pub_Usua_UsuModi { get; set; }
        public Nullable<System.DateTime> Pub_Usua_FecModi { get; set; }
        public int Pub_Usua_Identidad { get; set; }
        public string Pub_Area_Codigo { get; set; }
        public string Pub_Usua_Obs { get; set; }
        public string pub_dni { get; set; }
    }
}
